CREATE SEQUENCE magasinsequence
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 10
    CYCLE;


CREATE SEQUENCE mouvementsequence
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 10
    CYCLE;